[package]
name = "tbon"
version = "0.1.0"
authors = ["haydnv"]
edition = "2018"
description = "Tinychain Binary Object Notation is a compact and versatile streaming-friendly binary serialization format"
repository = "http://github.com/haydnv/tbon"
readme = "README.md"

categories = ["asynchronous", "encoding", "parser-implementations", "parsing", "web-programming"]
keywords = ["binary", "stream", "decode", "serialize", "deserialize"]


[dependencies]
